<?php
require "src/partial/header.php";
if(!is_logged_in()){
    header('Location: home');
}
if($_SESSION["type"]!=2){
    header('Location: home');
}
require_once "functions/managaUserController.php";

function debug_to_console($data) {
    $output = $data;
    if (is_array($output))
        $output = implode(',', $output);
  
    echo "<script>console.log('Debug Objects: " . $output . "' );</script>";
}

debug_to_console($_SESSION["email"]);
debug_to_console($_SESSION["user_id"]);
$db_handle = new DBController();
$query = "SELECT * FROM user ORDER BY surname";
$users = $db_handle->runQuery($query);
unset($db_handle);


?>


<div class="pageContainer">
<div class="usersContainerWrapper">
  
  <div class = "usersHeader">
    <div class ="surnameHeader">Surname</div>
    <div class ="nameHeader">Name</div>
    <div class ="emailHeader">Email</div>
    <div class ="priorityHeader">Priority</div>
    <div class ="typeHeader">Type</div>
    <div class ="passwordHeader">Password</div>
    <div class ="statusHeader">Status</div>
  </div>  
    <div class="userContainer" id="userContainer"></div>
<?php
if($users!=NULL){
    $nrOfUsers = count($users);
}else{
    $nrOfUsers = 0;
}
for ($i=0; $i<$nrOfUsers; $i++){
    echo('<form method="post" action="" class="user" >');//onsubmit="validateUserChange(event);"
    echo('<input type="hidden" name="id" value="' .$users[$i]["ID"]. '">');
    echo('<div class="surnameUser"><p>' . $users[$i]["surname"] . '</p></div>');
    echo('<div class="nameUser"><p>' . $users[$i]["name"] . '</p></div>');
    echo('<input class="emailUser" name="email" value="' . $users[$i]["email"] . '">');
    echo('<input class="priorityUser" type="number" name="priority"  min="1" max="99" value="' .$users[$i]["priority"]. '">');
    echo('<select name="usertype" id="type" class="typeUser">');
    if($users[$i]["type"]==1){
        echo('<option value="1">User</option>');
        echo('<option value="2">Admin</option>');
    }elseif($users[$i]["type"]==2){
        echo('<option value="2">Admin</option>');
        echo('<option value="1">User</option>');        
    }
    echo('</p></select>');
    echo('<div class="passwordButtonContainer"><input class="button" name="type" type="submit" value="Reset"></div>');
    if($users[$i]["status"]==0){
        echo('<div class="statusButtonContainer"><input class="button" name="type" type="submit" value="Disabled"></div>');
    }elseif($users[$i]["status"]==1){
        echo('<div class="statusButtonContainer"><input class="button" name="type" type="submit" value="Active"></div>');
    }
    echo('<div class="updateButtonContainer"><input class="button" name="type" type="submit" value="Update"></div>');
    echo('</form>');
}
?>

</div>

</div>
<?php




require "src/partial/footer.php";
?>