<?php
require "src/partial/header.php";
require "functions/presetGlobalController.php";
if($_SESSION["type"]!=2){
    header('Location: home');
}


function debug_to_console($data) {
    $output = $data;
    if (is_array($output))
        $output = implode(',', $output);
  
    echo "<script>console.log('Debug Objects: " . $output . "' );</script>";
}
$db_handle = new DBController();
$query = "SELECT * FROM preset_global ORDER BY name";
$presets = $db_handle->runQuery($query);
unset($db_handle);

if($_SERVER['REQUEST_METHOD'] == "POST")
  {
    if($_POST['type']=='Add'){
        $name = $_POST['name'];
        $width = $_POST['width'];
        $height = $_POST['height'];
        $bitrate = $_POST['bitrate'];
        $frameRate = $_POST['frameRate'];
        $audio = $_POST['audio'];
        $audioBitrate = $_POST['audioBitrate'];
        $mail = $_POST['mail'];
        instertPreset($presets,$name,$width,$height,$bitrate,$frameRate,$audio,$audioBitrate,$mail);
        header("Refresh:0");
    }elseif($_POST['type']=='Delete'){
        $db_handle = new DBController();
        error_log($_POST['id']);
        $queryDelete = 'DELETE FROM preset_global WHERE id=' . $_POST['id'];
        $db_handle->deleteQuery($queryDelete);
        unset($db_handle);
        header("Refresh:0");
    }else{
        $id = $_POST['id'];
        $name = $_POST['name'];
        $width = $_POST['width'];
        $height = $_POST['height'];
        $bitrate = $_POST['bitrate'];
        $frameRate = $_POST['frameRate'];
        $audio = $_POST['audio'];
        $audioBitrate = $_POST['audioBitrate'];
        $mail = $_POST['mail'];
        updatePreset($presets,$id,$name,$width,$height,$bitrate,$frameRate,$audio,$audioBitrate,$mail);
        header("Refresh:0");
    }
  }

?>
<div class="pageContainer">
<div class="presetContainerWrapper">
  
  <div class = "presetHeader">
    <div class ="nameHeader">Name</div>
    <div class ="codecHeader">Codec</div>
    <!-- <div class ="containerHeader">Container</div> -->
    <div class ="widthHeader">Width</div>
    <div class ="heightHeader">Height</div>
    <div class ="bitrateHeader">Bitrate</div>
    <div class ="frameRateHeader">Frame Rate</div>
    <div class ="audioHeader">Audio</div>
    <div class ="audioBitrateHeader">Audio bitrate</div>
    <div class ="mailHeader">Mail</div>
  </div>  
    <div class="presetContainer" id="presetContainer"></div>
<?php
if($presets!=NULL){
    $nrOfPresets = count($presets);
}else{
    $nrOfPresets = 0;
}
for ($i=0; $i<=$nrOfPresets; $i++){
    echo('<form method="post" action="" class="preset" onsubmit="validatePresetSubmission(event);">');
    echo('<input type="hidden" name="id" value="' .$presets[$i]["id"]. '">');
    echo('<input class ="namePreset" name="name" type="text"  value="' . $presets[$i]["name"] . '">');
    printf('<select class ="codecPreset" name="codec" disabled>
            <option class="optionLi" ' .(($presets[$i]["codec"]=='H.264')?'selected="selected"':""). ' value="H.264">H.264</option>
            <option class="optionLi" ' .(($presets[$i]["codec"]=='possible extend')?'selected="selected"':""). ' value="possible extend">possible extend</option>
            <option class="optionLi" value="H.264">H.264</option>
            </select>'
        );
    // echo('<div class ="containerPreset">' . $presets[$i]["name"] . "</div>" );
    echo('<input class ="widthPreset" name="width" type="number" min="1" max="4092" value="' . $presets[$i]["width"] . '">' );
    echo('<input class ="heightPreset" name="height" type="number" min="1" max="2160" value="' . $presets[$i]["height"] .  '">' );
    echo('<input class ="bitratePreset" name="bitrate" type="number" min="100" max="50000" value="' . $presets[$i]["bitrate"] . '">' );
    printf('<select class ="frameRatePreset" name="frameRate">
            <option class="optionLi" ' .(($presets[$i]["framerate"]=='25')?'selected="selected"':""). ' value="25">25</option>
            <option class="optionLi" ' .(($presets[$i]["framerate"]=='24')?'selected="selected"':""). ' value="24">24</option>
            <option class="optionLi" ' .(($presets[$i]["framerate"]=='29.97')?'selected="selected"':""). ' value="29.97">29.97</option>
            <option class="optionLi" ' .(($presets[$i]["framerate"]=='23.976')?'selected="selected"':""). ' value="23.976">23.976</option>
            <option class="optionLi" ' .(($presets[$i]["framerate"]=='60')?'selected="selected"':""). ' value="60">60</option>
            <option class="optionLi" ' .(($presets[$i]["framerate"]=='30')?'selected="selected"':""). ' value="30">30</option>
            </select>'
        );
    echo('<input class="audioPreset" name="audio" type="checkbox" ' .(($presets[$i]["audio"]=='1')?'checked="checked"':""). '>' );
    printf('<select class ="audioBitratePreset" name="audioBitrate">
            <option class="optionLi" ' .(($presets[$i]["audio_bitrate"]=='56')?'selected="selected"':""). ' value="56">56</option>
            <option class="optionLi" ' .(($presets[$i]["audio_bitrate"]=='96')?'selected="selected"':""). ' value="96">96</option>
            <option class="optionLi" ' .(($presets[$i]["audio_bitrate"]=='128')?'selected="selected"':""). ' value="128">128</option>
            <option class="optionLi" ' .(($presets[$i]["audio_bitrate"]=='160')?'selected="selected"':""). ' value="160">160</option>
            <option class="optionLi" ' .(($presets[$i]["audio_bitrate"]=='192')?'selected="selected"':""). ' value="192">192</option>
            <option class="optionLi" ' .(($presets[$i]["audio_bitrate"]=='224')?'selected="selected"':""). ' value="224">224</option>
            <option class="optionLi" ' .(($presets[$i]["audio_bitrate"]=='256')?'selected="selected"':""). ' value="256">256</option>
            <option class="optionLi" ' .(($presets[$i]["audio_bitrate"]=='320')?'selected="selected"':""). ' value="320">320</option>
            </select>'
        );
    echo('<input name="mail" class="mailPreset" type="checkbox" ' .(($presets[$i]["send_email"]=='1')?'checked="checked"':""). '>' );
    if($i<$nrOfPresets){
        echo('<div class="updateButtonContainer"><input class="button" name="type" type="submit" value="Update"></div>');
        echo('<div class="deleteButtonContainer"><input class="button" name="type" type="submit" value="Delete"></div>');
    }else{
        echo('<div class="updateButtonContainer"><input class="button" name="type" type="submit" value="Add"></div>');
    }
    echo('</form>');
}
?>

</div>

</div>
<?php
require "src/partial/footer.php";
?>

