<?php 
require "src/partial/header.php";
require "functions/registrationController.php";
if(is_logged_in()){
  header('Location: home');
}
?>


      <form id="form" method="post" onsubmit="return validateMyForm();" class="form">
        <h2>Register With Us</h2>
        <div class="form-control">
          <label for="firstname">Name</label>
          <input type="text" name="firstname" placeholder="Enter Name" />
          <small>Error Message</small>
        </div>
        <div class="form-control">
          <label for="surname">Surname</label>
          <input type="text" name="surname" placeholder="Enter Surname" />
          <small>Error Message</small>
        </div>
        <div class="form-control">
          <label for="email">Email</label>
          <input type="text" name="email" placeholder="Enter email" />
          <small>Error Message</small>
        </div>
        <div class="form-control">
          <label for="password">Password</label>
          <input type="password" name="password" placeholder="Enter password" />
          <small>Error Message</small>
        </div>
        <div class="form-control">
          <label for="password2">Confirm Password</label>
          <input type="password" name="password2" placeholder="Enter password again" />
          <small>Error Message</small>
        </div>
        <input type="submit" value="Submit" class="login-btn" />
      </form>
<?php
  require "src/partial/footer.php";
?>