<?php 
require "src/partial/header.php";
require_once "functions/connection.php";
require_once "functions/resetPasswordController.php";


if(is_logged_in()){
?>
<form id="form" method="post" onsubmit="return validateMyFormPassword();" action="" class="form">
        <div class="form-control">
          <label for="password">Password</label>
          <input type="password" name="password" placeholder="Enter current password" />
          <small>Error Message</small>
        </div>
        <div class="form-control">
          <label for="password2">New Password</label>
          <input type="password" name="password2" placeholder="Enter new password" />
          <small>Error Message</small>
        </div>
        <div class="form-control">
          <label for="password3">Confirm New Password</label>
          <input type="password" name="password3" placeholder="Enter new password again" />
          <small>Error Message</small>
        </div>
        <input type="submit" value="Submit" class="login-btn" />
</form>
<?php
}elseif ($_SERVER['REQUEST_METHOD'] === 'GET'){
    if(isset($_GET['email']) && isset($_GET['token'])){
        $email = $_GET['email'];
        $token = $_GET['token'];
        $db_handle = new DBController();
        $query = "SELECT * FROM password_resets WHERE email = '$email' AND token = '$token' AND created_at > DATE_SUB(NOW(), INTERVAL 1 HOUR)";
        $validToken = $db_handle->runQuery($query);
        unset($db_handle);
    if (!empty($validToken)) {
        ?>
        <form id="form" method="post" onsubmit="return validateMyFormNewPassword();" action="functions/resetPasswordController.php" class="form">
        <input type="hidden" name="user_id" value="<?php echo($validToken[0]['user_id']);?>">
        <div class="form-control">
          <label for="password2">New Password</label>
          <input type="password" name="password2" placeholder="Enter new password" />
          <small>Error Message</small>
        </div>
        <div class="form-control">
          <label for="password3">Confirm New Password</label>
          <input type="password" name="password3" placeholder="Enter new password again" />
          <small>Error Message</small>
        </div>
        <input type="submit" value="Submit" class="login-btn" />
        </form>
        <?php
    }else{
        echo '<script>alert("Invalid or expired link")</script>';
    }
    }else{
?>
<form id="form" method="post" onsubmit="return validateMyFormEmail();" action="" class="form">
        <div class="form-control">
          <label for="email">Email</label>
          <input type="text" name="email" placeholder="Enter email" />
          <small>Error Message</small>
        </div>
        <input type="submit" value="Request password reset" class="login-btn" />
</form>
<?php
}}
    require "src/partial/footer.php";
?>