<?php
require_once "src/partial/header.php";
require_once "functions/userSettingsController.php";
?>
<div class="pageContainer">
    <div class="form">
        <label for="cloud">Only cloud links</label>
        <input name="cloud" type="checkbox" onchange="updateCheckboxStatus(this, 'cloud')" <?php echo isset($status['cloud']) && $status['cloud'] ? 'checked="checked"' : ''; ?> />
        <label for="notification">Basic email notification</label>
        <input name="notification" type="checkbox" onchange="updateCheckboxStatus(this, 'notification')" <?php echo isset($status['notification']) && $status['notification'] ? 'checked="checked"' : ''; ?> />
        <div class="last-row">
            <button class="login-btn" onclick="redirect('/resetPassword')">Change password</button>
        </div>
    </div>
</div>
<?php
    echo '<script>const userId = "' . $_SESSION["user_id"] . '";</script>';
    require "src/partial/footer.php";
?>
</html>